name = "healthcheck"
main = "build/worker/shim.mjs"
compatibility_date = "2025-01-12"

preview_urls = false

[build]
command = "cargo install -q worker-build && worker-build --release"

[triggers]
crons = ["*/2 * * * *"]

[vars]
HEALTH_CHECK_URL = "https://redbeard.team/en/blog"

[observability]
enabled = true
head_sampling_rate = 1 #
